export const COUNTRY_OPTIONS = [
  { code: 'US', label: 'United States (+1)' },
  { code: 'GB', label: 'United Kingdom (+44)' },
  { code: 'CA', label: 'Canada (+1)' },
  { code: 'DE', label: 'Germany (+49)' },
  { code: 'FR', label: 'France (+33)' },
  { code: 'AU', label: 'Australia (+61)' },
  { code: 'IT', label: 'Italy (+39)' },
  { code: 'ES', label: 'Spain (+34)' },
  { code: 'JP', label: 'Japan (+81)' },
  { code: 'SG', label: 'Singapore (+65)' },
  { code: 'IN', label: 'India (+91)' },
  { code: 'BR', label: 'Brazil (+55)' },
  { code: 'MX', label: 'Mexico (+52)' },
  { code: 'ZA', label: 'South Africa (+27)' },
  { code: 'RU', label: 'Russia (+7)' },
  { code: 'CN', label: 'China (+86)' },
  { code: 'SE', label: 'Sweden (+46)' },
  { code: 'CH', label: 'Switzerland (+41)' },
  { code: 'NL', label: 'Netherlands (+31)' },
  { code: 'BE', label: 'Belgium (+32)' },
  { code: 'DK', label: 'Denmark (+45)' },
  { code: 'FI', label: 'Finland (+358)' },
  { code: 'NO', label: 'Norway (+47)' },
  { code: 'IE', label: 'Ireland (+353)' },
  { code: 'PL', label: 'Poland (+48)' },
  { code: 'PT', label: 'Portugal (+351)' },
  { code: 'AT', label: 'Austria (+43)' },
  { code: 'GR', label: 'Greece (+30)' },
  { code: 'TR', label: 'Turkey (+90)' },
  { code: 'IL', label: 'Israel (+972)' },
  { code: 'NZ', label: 'New Zealand (+64)' },
  { code: 'KR', label: 'South Korea (+82)' },
  { code: 'HK', label: 'Hong Kong (+852)' },
  { code: 'MY', label: 'Malaysia (+60)' },
  { code: 'TH', label: 'Thailand (+66)' },
  { code: 'ID', label: 'Indonesia (+62)' },
  { code: 'PH', label: 'Philippines (+63)' },
  { code: 'SA', label: 'Saudi Arabia (+966)' },
  { code: 'AE', label: 'United Arab Emirates (+971)' },
  { code: 'EG', label: 'Egypt (+20)' },
  { code: 'NG', label: 'Nigeria (+234)' },
  { code: 'KE', label: 'Kenya (+254)' },
  { code: 'AR', label: 'Argentina (+54)' },
  { code: 'CO', label: 'Colombia (+57)' },
  { code: 'CL', label: 'Chile (+56)' },
  { code: 'PE', label: 'Peru (+51)' },
  { code: 'VE', label: 'Venezuela (+58)' },
  { code: 'HU', label: 'Hungary (+36)' },
  { code: 'CZ', label: 'Czech Republic (+420)' },
  { code: 'SK', label: 'Slovakia (+421)' },
  { code: 'RO', label: 'Romania (+40)' },
  { code: 'BG', label: 'Bulgaria (+359)' },
  { code: 'HR', label: 'Croatia (+385)' },
  { code: 'SI', label: 'Slovenia (+386)' },
  { code: 'EE', label: 'Estonia (+372)' },
  { code: 'LV', label: 'Latvia (+371)' },
  { code: 'LT', label: 'Lithuania (+370)' },
  { code: 'LU', label: 'Luxembourg (+352)' },
  { code: 'IS', label: 'Iceland (+354)' },
  { code: 'MC', label: 'Monaco (+377)' },
  { code: 'LI', label: 'Liechtenstein (+423)' },
  { code: 'MT', label: 'Malta (+356)' },
  { code: 'CY', label: 'Cyprus (+357)' },
  { code: 'UA', label: 'Ukraine (+380)' },
  { code: 'BY', label: 'Belarus (+375)' },
  { code: 'MD', label: 'Moldova (+373)' },
  { code: 'GE', label: 'Georgia (+995)' },
  { code: 'AM', label: 'Armenia (+374)' },
  { code: 'AZ', label: 'Azerbaijan (+994)' },
  { code: 'KZ', label: 'Kazakhstan (+7)' },
  { code: 'UZ', label: 'Uzbekistan (+998)' },
  { code: 'KG', label: 'Kyrgyzstan (+996)' },
  { code: 'TJ', label: 'Tajikistan (+992)' },
  { code: 'TM', label: 'Turkmenistan (+993)' },
  { code: 'PK', label: 'Pakistan (+92)' },
  { code: 'BD', label: 'Bangladesh (+880)' },
  { code: 'LK', label: 'Sri Lanka (+94)' },
  { code: 'NP', label: 'Nepal (+977)' },
  { code: 'AF', label: 'Afghanistan (+93)' },
  { code: 'IR', label: 'Iran (+98)' },
  { code: 'IQ', label: 'Iraq (+964)' },
  { code: 'SY', label: 'Syria (+963)' },
  { code: 'JO', label: 'Jordan (+962)' },
  { code: 'LB', label: 'Lebanon (+961)' },
  { code: 'PS', label: 'Palestine (+970)' },
  { code: 'YE', label: 'Yemen (+967)' },
  { code: 'OM', label: 'Oman (+968)' },
  { code: 'QA', label: 'Qatar (+974)' },
  { code: 'BH', label: 'Bahrain (+973)' },
  { code: 'KW', label: 'Kuwait (+965)' },
  { code: 'DZ', label: 'Algeria (+213)' },
  { code: 'MA', label: 'Morocco (+212)' },
  { code: 'TN', label: 'Tunisia (+216)' },
  { code: 'SD', label: 'Sudan (+249)' },
  { code: 'ET', label: 'Ethiopia (+251)' },
  { code: 'TZ', label: 'Tanzania (+255)' },
  { code: 'UG', label: 'Uganda (+256)' },
  { code: 'GH', label: 'Ghana (+233)' },
  { code: 'CM', label: 'Cameroon (+237)' },
  { code: 'SN', label: 'Senegal (+221)' },
  { code: 'CI', label: 'Ivory Coast (+225)' },
  { code: 'MZ', label: 'Mozambique (+258)' },
  { code: 'AO', label: 'Angola (+244)' },
  { code: 'ZW', label: 'Zimbabwe (+263)' },
  { code: 'BW', label: 'Botswana (+267)' },
  { code: 'NA', label: 'Namibia (+264)' },
  { code: 'MW', label: 'Malawi (+265)' },
  { code: 'ZM', label: 'Zambia (+260)' },
  { code: 'MG', label: 'Madagascar (+261)' },
  { code: 'RE', label: 'Reunion (+262)' },
  { code: 'MU', label: 'Mauritius (+230)' },
  { code: 'SC', label: 'Seychelles (+248)' },
  { code: 'SS', label: 'South Sudan (+211)' },
  { code: 'CD', label: 'Congo (DRC) (+243)' },
  { code: 'CG', label: 'Congo (Republic) (+242)' },
  { code: 'GA', label: 'Gabon (+241)' },
  { code: 'GQ', label: 'Equatorial Guinea (+240)' },
  { code: 'CF', label: 'Central African Republic (+236)' },
  { code: 'TD', label: 'Chad (+235)' },
  { code: 'NE', label: 'Niger (+227)' },
  { code: 'ML', label: 'Mali (+223)' },
  { code: 'BF', label: 'Burkina Faso (+226)' },
  { code: 'TG', label: 'Togo (+228)' },
  { code: 'BJ', label: 'Benin (+229)' },
  { code: 'SL', label: 'Sierra Leone (+232)' },
  { code: 'LR', label: 'Liberia (+231)' },
  { code: 'GM', label: 'Gambia (+220)' },
  { code: 'GW', label: 'Guinea-Bissau (+245)' },
  { code: 'GN', label: 'Guinea (+224)' },
  { code: 'SO', label: 'Somalia (+252)' },
  { code: 'DJ', label: 'Djibouti (+253)' },
  { code: 'ER', label: 'Eritrea (+291)' },
  { code: 'SZ', label: 'Eswatini (+268)' },
  { code: 'LS', label: 'Lesotho (+266)' },
  { code: 'RW', label: 'Rwanda (+250)' },
  { code: 'BI', label: 'Burundi (+257)' },
  { code: 'CV', label: 'Cape Verde (+238)' },
  { code: 'ST', label: 'Sao Tome and Principe (+239)' },
];

export const COUNTRY_CODE_MAP: Record<string, string> = Object.fromEntries(
  COUNTRY_OPTIONS.map(opt => [opt.code, opt.label.match(/\((\+?\d+)\)/)?.[1].replace('+', '') || ''])
);
